# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('status', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField()),
                ('authentication_token', models.CharField(max_length=255)),
                ('profile_picture', models.CharField(max_length=255)),
                ('future_events', models.ManyToManyField(to='events.UserEvents')),
            ],
        ),
    ]
