# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20161023_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='User',
        ),
    ]
