# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.ImageField(blank=True, null=True, upload_to=upload.models.upload_to, verbose_name='image')),
            ],
        ),
    ]
