# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='username',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
    ]
